env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

language: php
os: linux
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

cache:
    directories:
        - "$HOME/.composer/cache"

before_script:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - ./vendor/bin/nunjuck -p $PHP_BIN -s -c ./tests/php.ini ./tests

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Sniffer
            script:
                - composer cs

        -   stage: Static Analysis
            script:
                - composer phpstan

        -   stage: Code Coverage
            script:
                - composer coverage
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml

    allow_failures:
        -   stage: Static Analysis
        -   stage: Code Coverage
        -   php: 7.4
        -   php: nightly

notifications:
    email: false
